// Generated by LiveScript 1.3.1
(function(){
  var fs, cheerio, request, async, cols, tasks;
  fs = require('fs');
  cheerio = require('cheerio');
  request = require('request');
  async = require('async');
  cols = ['town', 'village', 'name'];
  tasks = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].map(function(page){
    return function(cb){
      return request.get("http://axe-level-1.herokuapp.com/lv2/?page=" + page, function(error, res, body){
        var $, row, data, i, d;
        $ = cheerio.load(body);
        row = $('table.table tr').first().next();
        data = [];
        while (row.text()) {
          data.push((fn$()));
          row = row.next();
        }
        return cb(null, data);
        function fn$(){
          var i$, ref$, len$, resultObj$ = {};
          for (i$ = 0, len$ = (ref$ = row.children().map(fn$).toArray()).length; i$ < len$; ++i$) {
            i = i$;
            d = ref$[i$];
            resultObj$[cols[i]] = d;
          }
          return resultObj$;
          function fn$(arg$, it){
            return $(it).text();
          }
        }
      });
    };
  });
  async.series(tasks, function(error, result){
    var data;
    data = result.reduce(function(prev, cur){
      return prev.concat(cur);
    });
    return fs.writeFileSync('output.json', JSON.stringify(
    data));
  });
}).call(this);
