// Generated by LiveScript 1.3.1
(function(){
  var fs, cheerio, request, async, listsToObj, columns, data, tasks, res$, i$;
  fs = require('fs');
  cheerio = require('cheerio');
  request = require('request');
  async = require('async');
  listsToObj = require('prelude-ls').listsToObj;
  columns = ['town', 'village', 'name'];
  data = [];
  res$ = [];
  for (i$ = 1; i$ <= 12; ++i$) {
    res$.push((fn$.call(this, i$)));
  }
  tasks = res$;
  async.parallel(tasks, function(error, result){
    var i$, len$, d;
    for (i$ = 0, len$ = result.length; i$ < len$; ++i$) {
      d = result[i$];
      data = data.concat(d);
    }
    return fs.writeFileSync('output.json', JSON.stringify(
    data));
  });
  function fn$(i){
    return function(cb){
      return request.get("http://axe-level-1.herokuapp.com/lv2/?page=" + i, function(error, res, body){
        var $, row, d;
        $ = cheerio.load(body);
        row = $('table.table tr').first().next();
        d = [];
        while (row.text()) {
          d.push(listsToObj(columns, row.children().map(fn$).toArray()));
          row = row.next();
        }
        return cb(null, d);
        function fn$(i, d){
          return $(d).text();
        }
      });
    };
  }
}).call(this);
