// Generated by LiveScript 1.2.0
var cheerio, request, fs, listsToObj, data;
cheerio = require('cheerio');
request = require('request');
fs = require('fs');
listsToObj = require('prelude-ls').listsToObj;
data = [];
request.get('http://axe-level-1.herokuapp.com/', function(error, response, body){
  var $, subjects, row, columns, name;
  $ = cheerio.load(body);
  subjects = $('table.table tr').first().children().map(function(i, e){
    return $(e).text();
  });
  subjects = subjects.toArray();
  subjects.shift();
  row = $('table.table tr').first().next();
  while (row.text()) {
    columns = row.children().map(fn$);
    columns = columns.toArray();
    name = columns.shift();
    data.push({
      name: name,
      grades: listsToObj(subjects, columns.map(fn1$))
    });
    row = row.next();
  }
  return fs.writeFileSync('output.json', JSON.stringify(
  data));
  function fn$(i, e){
    return $(e).text();
  }
  function fn1$(it){
    return +it;
  }
});