// Generated by LiveScript 1.3.1
(function(){
  var cheerio, request, fs, data;
  cheerio = require('cheerio');
  request = require('request');
  fs = require('fs');
  data = [];
  request.get('http://axe-level-1.herokuapp.com/', function(error, response, body){
    var $, subjects, row, columns, name, i, g;
    $ = cheerio.load(body);
    subjects = $('table.table tr').first().children().map(function(i, e){
      return $(e).text();
    });
    subjects = subjects.toArray();
    subjects.shift();
    row = $('table.table tr').first().next();
    while (row.text()) {
      columns = row.children().map(fn$);
      columns = columns.toArray();
      name = columns.shift();
      data.push({
        name: name,
        grades: (fn1$())
      });
      row = row.next();
    }
    return fs.writeFileSync('output.json', JSON.stringify(
    data));
    function fn$(i, e){
      return $(e).text();
    }
    function fn1$(){
      var i$, ref$, len$, resultObj$ = {};
      for (i$ = 0, len$ = (ref$ = columns.map(fn$)).length; i$ < len$; ++i$) {
        i = i$;
        g = ref$[i$];
        resultObj$[subjects[i]] = g;
      }
      return resultObj$;
      function fn$(it){
        return +it;
      }
    }
  });
}).call(this);
